### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nico75005** [thefuntasty/Sonar#2]
Any plan on updating the library to Swift 3?

Cheers

**Comment by kafejo** [comment]
Well I can take a look at it, did know that someone is using it 🙂

**Comment by vishalcnz** [comment]
Please update this library to Swift 3 
 
Thanks in Advance

**Comment by mamdouhweb** [comment]
@kafejo 
Sent Pull request https://github.com/thefuntasty/Sonar/pull/3 that would help resolving this isuue

**Comment by mamdouhweb** [comment]
@kafejo 
Pull request #3 is updated to work with swift 3 and animation. It would be great if you setup a new release.
Thanks!

**Comment by kafejo** [comment]
I've just updated example and the project to Swift 3 as well. I have a problem with changes of ownership of the project though. I've opened a dispute and once I have the ownership back I will publish new version to Cocoapods. You can point directly to the repository for now:

```
pod 'Sonar', :git => 'https://github.com/thefuntasty/Sonar.git', :tag => '3.0.0'
```

**Comment by kafejo** [comment]
Version 3.0.0 also available on cocoapods now 😊
